--
-- PostgreSQL database dump
--

-- Dumped from database version 15.2
-- Dumped by pg_dump version 15.2

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


ALTER TABLE public.auth_group OWNER TO postgres;

--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_group_permissions OWNER TO postgres;

--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


ALTER TABLE public.auth_permission OWNER TO postgres;

--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user (
    id integer NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    email character varying(254) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL
);


ALTER TABLE public.auth_user OWNER TO postgres;

--
-- Name: auth_user_groups; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_groups (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    group_id integer NOT NULL
);


ALTER TABLE public.auth_user_groups OWNER TO postgres;

--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_user_user_permissions; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.auth_user_user_permissions (
    id bigint NOT NULL,
    user_id integer NOT NULL,
    permission_id integer NOT NULL
);


ALTER TABLE public.auth_user_user_permissions OWNER TO postgres;

--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.auth_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id integer NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


ALTER TABLE public.django_admin_log OWNER TO postgres;

--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


ALTER TABLE public.django_content_type OWNER TO postgres;

--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


ALTER TABLE public.django_migrations OWNER TO postgres;

--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


ALTER TABLE public.django_session OWNER TO postgres;

--
-- Name: loginInfo; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public."loginInfo" (
    id bigint NOT NULL,
    name character varying(50) NOT NULL,
    passw bigint NOT NULL,
    mail character varying(50)
);


ALTER TABLE public."loginInfo" OWNER TO postgres;

--
-- Name: loginInfo_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public."loginInfo" ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."loginInfo_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_carousel; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_carousel (
    id bigint NOT NULL,
    title character varying(200),
    cover_image character varying(100),
    status character varying(10) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL
);


ALTER TABLE public.main_carousel OWNER TO postgres;

--
-- Name: main_carousel_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_carousel ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_carousel_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: main_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.main_userprofile (
    id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.main_userprofile OWNER TO postgres;

--
-- Name: main_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.main_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.main_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pazar_category; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pazar_category (
    id bigint NOT NULL,
    title character varying(50) NOT NULL,
    slug character varying(50) NOT NULL
);


ALTER TABLE public.pazar_category OWNER TO postgres;

--
-- Name: pazar_category_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pazar_category ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pazar_category_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: pazar_product; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.pazar_product (
    id bigint NOT NULL,
    title character varying(50) NOT NULL,
    slug character varying(50) NOT NULL,
    description text NOT NULL,
    price integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    "updated_At" timestamp with time zone NOT NULL,
    category_id bigint NOT NULL,
    user_id integer NOT NULL,
    image character varying(100)
);


ALTER TABLE public.pazar_product OWNER TO postgres;

--
-- Name: pazar_product_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.pazar_product ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pazar_product_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: profiller_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.profiller_userprofile (
    id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.profiller_userprofile OWNER TO postgres;

--
-- Name: profiller_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.profiller_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.profiller_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: userprofile_userprofile; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.userprofile_userprofile (
    id bigint NOT NULL,
    user_id integer NOT NULL
);


ALTER TABLE public.userprofile_userprofile OWNER TO postgres;

--
-- Name: userprofile_userprofile_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.userprofile_userprofile ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.userprofile_userprofile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: auth_group; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group (id, name) FROM stdin;
\.


--
-- Data for Name: auth_group_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_group_permissions (id, group_id, permission_id) FROM stdin;
\.


--
-- Data for Name: auth_permission; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_permission (id, name, content_type_id, codename) FROM stdin;
1	Can add log entry	1	add_logentry
2	Can change log entry	1	change_logentry
3	Can delete log entry	1	delete_logentry
4	Can view log entry	1	view_logentry
5	Can add permission	2	add_permission
6	Can change permission	2	change_permission
7	Can delete permission	2	delete_permission
8	Can view permission	2	view_permission
9	Can add group	3	add_group
10	Can change group	3	change_group
11	Can delete group	3	delete_group
12	Can view group	3	view_group
13	Can add user	4	add_user
14	Can change user	4	change_user
15	Can delete user	4	delete_user
16	Can view user	4	view_user
17	Can add content type	5	add_contenttype
18	Can change content type	5	change_contenttype
19	Can delete content type	5	delete_contenttype
20	Can view content type	5	view_contenttype
21	Can add session	6	add_session
22	Can change session	6	change_session
23	Can delete session	6	delete_session
24	Can view session	6	view_session
25	Can add userprofile	7	add_userprofile
26	Can change userprofile	7	change_userprofile
27	Can delete userprofile	7	delete_userprofile
28	Can view userprofile	7	view_userprofile
29	Can add category	9	add_category
30	Can change category	9	change_category
31	Can delete category	9	delete_category
32	Can view category	9	view_category
33	Can add userprofile	8	add_userprofile
34	Can change userprofile	8	change_userprofile
35	Can delete userprofile	8	delete_userprofile
36	Can view userprofile	8	view_userprofile
37	Can add product	10	add_product
38	Can change product	10	change_product
39	Can delete product	10	delete_product
40	Can view product	10	view_product
41	Can add userprofile	11	add_userprofile
42	Can change userprofile	11	change_userprofile
43	Can delete userprofile	11	delete_userprofile
44	Can view userprofile	11	view_userprofile
45	Can add carousel	12	add_carousel
46	Can change carousel	12	change_carousel
47	Can delete carousel	12	delete_carousel
48	Can view carousel	12	view_carousel
49	Can add page	13	add_page
50	Can change page	13	change_page
51	Can delete page	13	delete_page
52	Can view page	13	view_page
\.


--
-- Data for Name: auth_user; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user (id, password, last_login, is_superuser, username, first_name, last_name, email, is_staff, is_active, date_joined) FROM stdin;
1	pbkdf2_sha256$390000$3R1Wca4WdcWX4wBV633AGe$oEPWbtPBY0sWLyt/SMjuru+50S+GYR4KdMb8WEGGAO4=	2023-04-05 01:11:17.423469+03	t	admin	Furkan	Alkılıç	adminboss@gmail.com	t	t	2023-03-27 01:30:01+03
3	pbkdf2_sha256$390000$RBdSA235SER90EjJbscF2z$YBEmp7EJNL9kit1KYLZsCF4bFUzKDmblNRF8oKYK9rY=	2023-04-07 02:06:40.549615+03	f	sahibinden				f	t	2023-04-03 23:40:53.785638+03
\.


--
-- Data for Name: auth_user_groups; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_groups (id, user_id, group_id) FROM stdin;
\.


--
-- Data for Name: auth_user_user_permissions; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.auth_user_user_permissions (id, user_id, permission_id) FROM stdin;
\.


--
-- Data for Name: django_admin_log; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_admin_log (id, action_time, object_id, object_repr, action_flag, change_message, content_type_id, user_id) FROM stdin;
1	2023-03-27 19:22:41.337258+03	1	Userprofile object (1)	1	[{"added": {}}]	8	1
2	2023-03-27 19:23:02.202037+03	1	Userprofile object (1)	3		8	1
3	2023-03-27 19:23:16.157286+03	2	Userprofile object (2)	1	[{"added": {}}]	8	1
4	2023-03-27 19:23:35.699325+03	2	Userprofile object (2)	2	[]	8	1
5	2023-03-27 19:26:58.91772+03	2	Userprofile object (2)	3		8	1
6	2023-03-27 19:27:04.108173+03	3	Userprofile object (3)	1	[{"added": {}}]	8	1
7	2023-03-27 19:30:20.7104+03	3	Userprofile object (3)	3		8	1
8	2023-03-27 19:30:33.436419+03	4	Userprofile object (4)	1	[{"added": {}}]	8	1
9	2023-03-27 20:14:45.214053+03	1	Category object (1)	1	[{"added": {}}]	9	1
10	2023-03-27 20:15:15.503879+03	2	Category object (2)	1	[{"added": {}}]	9	1
11	2023-03-27 20:33:55.030007+03	1	Vestel Buzdolabı 2023 Model	1	[{"added": {}}]	10	1
12	2023-03-28 16:10:27.732005+03	2	Arçelik No Frost Buzdolabı 2023 Model	1	[{"added": {}}]	10	1
13	2023-03-28 16:11:54.080331+03	1	admin	2	[{"changed": {"fields": ["First name", "Last name"]}}]	4	1
14	2023-03-28 16:55:26.330615+03	1	Vestel Buzdolabı 2023 Model	2	[{"changed": {"fields": ["Image"]}}]	10	1
15	2023-03-28 16:55:30.89885+03	2	Arçelik No Frost Buzdolabı 2023 Model	2	[{"changed": {"fields": ["Image"]}}]	10	1
16	2023-03-28 17:15:27.460519+03	2	Arçelik No Frost Buzdolabı 2023 Model	2	[{"changed": {"fields": ["Image"]}}]	10	1
17	2023-03-28 17:15:32.916495+03	2	Arçelik No Frost Buzdolabı 2023 Model	2	[{"changed": {"fields": ["Image"]}}]	10	1
18	2023-03-28 17:16:11.403592+03	2	Arçelik No Frost Buzdolabı 2023 Model	2	[{"changed": {"fields": ["Image"]}}]	10	1
19	2023-03-28 17:16:16.082841+03	2	Arçelik No Frost Buzdolabı 2023 Model	2	[{"changed": {"fields": ["Image"]}}]	10	1
20	2023-03-28 18:47:40.973492+03	2	Arçelik No Frost Buzdolabı 2023 Model	2	[{"changed": {"fields": ["Description"]}}]	10	1
21	2023-03-29 00:49:17.323721+03	2	Çamaşır Makinesi	2	[{"changed": {"fields": ["Title", "Slug"]}}]	9	1
22	2023-03-29 00:49:30.166716+03	1	Buzdolabı	2	[{"changed": {"fields": ["Title", "Slug"]}}]	9	1
23	2023-03-30 16:42:27.658818+03	2	sahibinden	1	[{"added": {}}]	4	1
24	2023-04-03 22:42:03.363525+03	2	sahibinden	2	[{"changed": {"fields": ["password"]}}]	4	1
25	2023-04-03 22:50:23.456494+03	2	sahibinden	3		4	1
26	2023-04-04 02:35:09.838872+03	1	Carousel object (1)	1	[{"added": {}}]	12	1
27	2023-04-05 01:11:46.806821+03	3	Bosch Çamaşır Makinesi 2023	3		10	1
28	2023-04-05 01:11:49.703826+03	4	Bosch Çamaşır Makinesi 2023	3		10	1
29	2023-04-05 01:11:52.162784+03	5	Bosch Çamaşır Makinesi 2023	3		10	1
30	2023-04-05 01:11:54.967668+03	6	Bosch Çamaşır Makinesi 2023	3		10	1
31	2023-04-05 01:11:57.061293+03	7	Bosch Çamaşır Makinesi 2023	3		10	1
32	2023-04-05 01:11:59.216621+03	8	Bosch Çamaşır Makinesi 2023	3		10	1
33	2023-04-05 01:12:01.394344+03	9	Bosch Çamaşır Makinesi 2023	3		10	1
34	2023-04-05 01:12:03.173964+03	10	Bosch Çamaşır Makinesi 2023	3		10	1
35	2023-04-05 01:12:05.06267+03	11	Bosch Çamaşır Makinesi 2023	3		10	1
\.


--
-- Data for Name: django_content_type; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_content_type (id, app_label, model) FROM stdin;
1	admin	logentry
2	auth	permission
3	auth	group
4	auth	user
5	contenttypes	contenttype
6	sessions	session
7	main	userprofile
8	userprofile	userprofile
9	pazar	category
10	pazar	product
11	profiller	userprofile
12	main	carousel
13	main	page
\.


--
-- Data for Name: django_migrations; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_migrations (id, app, name, applied) FROM stdin;
1	contenttypes	0001_initial	2023-03-27 01:29:08.995105+03
2	auth	0001_initial	2023-03-27 01:29:09.043521+03
3	admin	0001_initial	2023-03-27 01:29:09.065524+03
4	admin	0002_logentry_remove_auto_add	2023-03-27 01:29:09.069525+03
5	admin	0003_logentry_add_action_flag_choices	2023-03-27 01:29:09.073526+03
6	contenttypes	0002_remove_content_type_name	2023-03-27 01:29:09.083418+03
7	auth	0002_alter_permission_name_max_length	2023-03-27 01:29:09.087419+03
8	auth	0003_alter_user_email_max_length	2023-03-27 01:29:09.091419+03
9	auth	0004_alter_user_username_opts	2023-03-27 01:29:09.09542+03
10	auth	0005_alter_user_last_login_null	2023-03-27 01:29:09.101421+03
11	auth	0006_require_contenttypes_0002	2023-03-27 01:29:09.102422+03
12	auth	0007_alter_validators_add_error_messages	2023-03-27 01:29:09.106423+03
13	auth	0008_alter_user_username_max_length	2023-03-27 01:29:09.113425+03
14	auth	0009_alter_user_last_name_max_length	2023-03-27 01:29:09.118425+03
15	auth	0010_alter_group_name_max_length	2023-03-27 01:29:09.124427+03
16	auth	0011_update_proxy_permissions	2023-03-27 01:29:09.129428+03
17	auth	0012_alter_user_first_name_max_length	2023-03-27 01:29:09.134429+03
18	sessions	0001_initial	2023-03-27 01:29:09.142331+03
19	main	0001_initial	2023-03-27 18:34:55.778178+03
20	pazar	0001_initial	2023-03-27 18:53:40.009654+03
21	userprofile	0001_initial	2023-03-27 18:53:40.023657+03
22	pazar	0002_alter_category_options_product	2023-03-27 20:32:01.67341+03
23	pazar	0003_alter_product_options_product_image	2023-03-28 16:55:00.713144+03
24	profiller	0001_initial	2023-03-30 02:26:38.40441+03
25	main	0002_alter_userprofile_options	2023-03-30 03:42:21.681495+03
26	pazar	0004_alter_category_options_alter_product_options	2023-03-30 03:42:21.690497+03
27	profiller	0002_alter_userprofile_options	2023-03-30 03:42:21.696498+03
28	main	0003_carousel_page	2023-04-04 02:32:47.174832+03
29	main	0004_delete_page_rename_createt_at_carousel_created_at	2023-04-04 04:14:30.629703+03
\.


--
-- Data for Name: django_session; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.django_session (session_key, session_data, expire_date) FROM stdin;
7owct9pl8ig7r5gzqz0hudo519n9gji1	.eJxVjEsOAiEQBe_C2hCh-enSvWcg3dDIqIFkmFkZ766TzEK3r6reS0RclxrXwXOcsjgLEIffjTA9uG0g37Hduky9LfNEclPkToe89szPy-7-HVQc9VsT-RA8KY1Gm-KOBax2XDSyJSjaswqA2TMlo4tN4C2Ek8tALtiEpMT7A-aCOAY:1pkYgi:_4tmuIzH36LDznOg19wFA_Ap-wzm68dRgodjnV13SDc	2023-04-21 02:06:40.555616+03
\.


--
-- Data for Name: loginInfo; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public."loginInfo" (id, name, passw, mail) FROM stdin;
1	admin	12345	adminboss@gmail.com
\.


--
-- Data for Name: main_carousel; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_carousel (id, title, cover_image, status, created_at, updated_at) FROM stdin;
1	Code	carousel/coding.png	published	2023-04-04 02:35:09.837871+03	2023-04-04 02:35:09.837871+03
\.


--
-- Data for Name: main_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.main_userprofile (id, user_id) FROM stdin;
\.


--
-- Data for Name: pazar_category; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pazar_category (id, title, slug) FROM stdin;
2	Çamaşır Makinesi	camasir-makinesi
1	Buzdolabı	buzdolabi
\.


--
-- Data for Name: pazar_product; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.pazar_product (id, title, slug, description, price, created_at, "updated_At", category_id, user_id, image) FROM stdin;
1	Vestel Buzdolabı 2023 Model	vestel-buzdolabi-2023	Mükemmel kalite 2023 model buzdolabı.	25000	2023-03-27 20:33:55.028005+03	2023-03-28 16:55:26.329615+03	1	1	uploads/product_images/20264834_r1_1000_1000.jpg
2	Arçelik No Frost Buzdolabı 2023 Model	arcelik-no-frost-buzdolabi-2023	Derin dondurucu özelliğiyle karşınızda Arçelik No Frost	33000	2023-03-28 16:10:27.724205+03	2023-03-28 18:47:40.97249+03	1	1	uploads/product_images/Arcelik-584611-EI-Capraz-Gorunum_4DHvZCM.jpg
12	Bosch Çamaşır Makinesi 2022	bosch-camasr-makinesi-2023	Stokta sınırlı sayıda bulunan bu ürünümüz indirimli fiyatındadır. 2022 model	29000	2023-04-05 01:43:58.040115+03	2023-04-05 03:36:36.901256+03	2	3	uploads/product_images/110000111273555_z26aSRQ.jpg
13	Siemens Buzdolabı 2022 Model	siemens-buzdolab-2022	Stoklarımızda sayılı kalan bu ürünü kaçırmayın.	19000	2023-04-07 14:57:55.429008+03	2023-04-07 14:58:24.044806+03	1	3	uploads/product_images/image.png
\.


--
-- Data for Name: profiller_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.profiller_userprofile (id, user_id) FROM stdin;
1	3
\.


--
-- Data for Name: userprofile_userprofile; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.userprofile_userprofile (id, user_id) FROM stdin;
4	1
\.


--
-- Name: auth_group_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_id_seq', 1, false);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_group_permissions_id_seq', 1, false);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_permission_id_seq', 52, true);


--
-- Name: auth_user_groups_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_groups_id_seq', 1, false);


--
-- Name: auth_user_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_id_seq', 3, true);


--
-- Name: auth_user_user_permissions_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.auth_user_user_permissions_id_seq', 1, false);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_admin_log_id_seq', 35, true);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_content_type_id_seq', 13, true);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.django_migrations_id_seq', 29, true);


--
-- Name: loginInfo_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."loginInfo_id_seq"', 1, true);


--
-- Name: main_carousel_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_carousel_id_seq', 1, true);


--
-- Name: main_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.main_userprofile_id_seq', 1, false);


--
-- Name: pazar_category_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pazar_category_id_seq', 2, true);


--
-- Name: pazar_product_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.pazar_product_id_seq', 13, true);


--
-- Name: profiller_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.profiller_userprofile_id_seq', 1, true);


--
-- Name: userprofile_userprofile_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.userprofile_userprofile_id_seq', 4, true);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_pkey PRIMARY KEY (id);


--
-- Name: auth_user_groups auth_user_groups_user_id_group_id_94350c0c_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_group_id_94350c0c_uniq UNIQUE (user_id, group_id);


--
-- Name: auth_user auth_user_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_permission_id_14a6b632_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_permission_id_14a6b632_uniq UNIQUE (user_id, permission_id);


--
-- Name: auth_user auth_user_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user
    ADD CONSTRAINT auth_user_username_key UNIQUE (username);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: loginInfo loginInfo_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public."loginInfo"
    ADD CONSTRAINT "loginInfo_pkey" PRIMARY KEY (id);


--
-- Name: main_carousel main_carousel_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_carousel
    ADD CONSTRAINT main_carousel_pkey PRIMARY KEY (id);


--
-- Name: main_userprofile main_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_userprofile
    ADD CONSTRAINT main_userprofile_pkey PRIMARY KEY (id);


--
-- Name: main_userprofile main_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_userprofile
    ADD CONSTRAINT main_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: pazar_category pazar_category_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pazar_category
    ADD CONSTRAINT pazar_category_pkey PRIMARY KEY (id);


--
-- Name: pazar_product pazar_product_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pazar_product
    ADD CONSTRAINT pazar_product_pkey PRIMARY KEY (id);


--
-- Name: profiller_userprofile profiller_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiller_userprofile
    ADD CONSTRAINT profiller_userprofile_pkey PRIMARY KEY (id);


--
-- Name: profiller_userprofile profiller_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiller_userprofile
    ADD CONSTRAINT profiller_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: userprofile_userprofile userprofile_userprofile_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userprofile_userprofile
    ADD CONSTRAINT userprofile_userprofile_pkey PRIMARY KEY (id);


--
-- Name: userprofile_userprofile userprofile_userprofile_user_id_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userprofile_userprofile
    ADD CONSTRAINT userprofile_userprofile_user_id_key UNIQUE (user_id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: auth_user_groups_group_id_97559544; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_group_id_97559544 ON public.auth_user_groups USING btree (group_id);


--
-- Name: auth_user_groups_user_id_6a12ed8b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_groups_user_id_6a12ed8b ON public.auth_user_groups USING btree (user_id);


--
-- Name: auth_user_user_permissions_permission_id_1fbb5f2c; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_permission_id_1fbb5f2c ON public.auth_user_user_permissions USING btree (permission_id);


--
-- Name: auth_user_user_permissions_user_id_a95ead1b; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_user_permissions_user_id_a95ead1b ON public.auth_user_user_permissions USING btree (user_id);


--
-- Name: auth_user_username_6821ab7c_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX auth_user_username_6821ab7c_like ON public.auth_user USING btree (username varchar_pattern_ops);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: pazar_category_slug_1a90e7de; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pazar_category_slug_1a90e7de ON public.pazar_category USING btree (slug);


--
-- Name: pazar_category_slug_1a90e7de_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pazar_category_slug_1a90e7de_like ON public.pazar_category USING btree (slug varchar_pattern_ops);


--
-- Name: pazar_product_category_id_f8da04f8; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pazar_product_category_id_f8da04f8 ON public.pazar_product USING btree (category_id);


--
-- Name: pazar_product_slug_bd2ba90e; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pazar_product_slug_bd2ba90e ON public.pazar_product USING btree (slug);


--
-- Name: pazar_product_slug_bd2ba90e_like; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pazar_product_slug_bd2ba90e_like ON public.pazar_product USING btree (slug varchar_pattern_ops);


--
-- Name: pazar_product_user_id_0dc332fd; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX pazar_product_user_id_0dc332fd ON public.pazar_product USING btree (user_id);


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_group_id_97559544_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_group_id_97559544_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_groups auth_user_groups_user_id_6a12ed8b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_groups
    ADD CONSTRAINT auth_user_groups_user_id_6a12ed8b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permi_permission_id_1fbb5f2c_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_user_user_permissions auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.auth_user_user_permissions
    ADD CONSTRAINT auth_user_user_permissions_user_id_a95ead1b_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: main_userprofile main_userprofile_user_id_15c416f4_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.main_userprofile
    ADD CONSTRAINT main_userprofile_user_id_15c416f4_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pazar_product pazar_product_category_id_f8da04f8_fk_pazar_category_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pazar_product
    ADD CONSTRAINT pazar_product_category_id_f8da04f8_fk_pazar_category_id FOREIGN KEY (category_id) REFERENCES public.pazar_category(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: pazar_product pazar_product_user_id_0dc332fd_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.pazar_product
    ADD CONSTRAINT pazar_product_user_id_0dc332fd_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: profiller_userprofile profiller_userprofile_user_id_4ef4e983_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.profiller_userprofile
    ADD CONSTRAINT profiller_userprofile_user_id_4ef4e983_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: userprofile_userprofile userprofile_userprofile_user_id_59dda034_fk_auth_user_id; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.userprofile_userprofile
    ADD CONSTRAINT userprofile_userprofile_user_id_59dda034_fk_auth_user_id FOREIGN KEY (user_id) REFERENCES public.auth_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

